### PR TITLE
Add new devices

### PR DESCRIPTION
**Pull request by MrOlolo**
Sync with https://gist.github.com/adamawolf/3048717

### CODE REVIEW

**Comment by colincameron** [comment]
This PR doesn't just add new devices, it also renames a large number of existing identifiers.

The naming is also inconsistent, e.g. why is `"iPad2,1": "iPad 2nd Gen (WiFi)"` changed to `"iPad2,1": "2nd Gen iPad"`, but `"iPad7,5": "iPad 6th Gen (WiFi)"` retains the iPad name before the generation?

**Comment by MrOlolo** [comment]
> This PR doesn't just add new devices, it also renames a large number of existing identifiers.
> 
> The naming is also inconsistent, e.g. why is `"iPad2,1": "iPad 2nd Gen (WiFi)"` changed to `"iPad2,1": "2nd Gen iPad"`, but `"iPad7,5": "iPad 6th Gen (WiFi)"` retains the iPad name before the generation?

Good question, but i don't have answer for it) I just used script from this repo to fetch data from @adamwolf gist

**Comment by timdiggins** [comment]
Thanks for the contribution @MrOlolo and thanks for the review @colincameron The naming here doesn't quite match the naming in the @adamwolf gist. The names are slightly variable worldwide and in different communications, but @pschmidtboeing and I both reviewed the names against Apple's comms and for consistency when I set up this repo. 

@MrOlolo would you mind changing the PR to just have the new devices?

**Comment by MrOlolo** [comment]
> @MrOlolo would you mind changing the PR to just have the new devices?

Done

**Pull request merged**
